import * as React from "react";

export default function Page() {
    return(
        <>
        <title>Présentation</title>
        <meta name="description" content="Generated by create next app for Seconde Page" />
        <div className="bg-background">
            <div className="text-white">
                <h1>Bienvenue sur SecureShare - Votre Plateforme de Chiffrement et Déchiffrement Sécurisé</h1>
                <br></br>
                <h2><u>Qui Sommes-Nous ?</u></h2>
                <p>Nous sommes une équipe d'étudiants passionnés en école d'ingénierie, déterminés à mettre en œuvre nos connaissances pour créer des solutions innovantes répondant aux besoins de sécurité de notre époque. Guidés par notre engagement envers la confidentialité et la protection des données, nous avons développé une application web de chiffrement et déchiffrement qui garantit la sécurité et la confidentialité des communications de nos utilisateurs.</p>
                <br></br>
                <h2><u>Notre Mission</u></h2>
                <p>Notre mission est de fournir à nos utilisateurs un moyen simple et efficace de protéger leurs données sensibles contre toute interception ou accès non autorisé. Nous croyons fermement que chacun devrait avoir le contrôle total de sa vie privée en ligne, et c'est pourquoi nous avons conçu notre plateforme pour offrir un chiffrement robuste et une confidentialité absolue.</p>
                <br></br>
                <h2><u>Notre Solution</u></h2>
                <p>Notre application web de chiffrement et déchiffrement repose sur des algorithmes de cryptographie avancés, assurant une sécurité maximale à chaque étape du processus. Que vous soyez un particulier soucieux de protéger vos communications ou une entreprise cherchant à sécuriser ses données sensibles, notre solution est conçue pour répondre à vos besoins en matière de confidentialité.</p>
                <br></br>
                <h2><u>Fonctionnalités Principales</u></h2>
                <ul>
                <li><strong>Chiffrement et Déchiffrement Sécurisés</strong> : Notre application vous permet de chiffrer et déchiffrer vos données en toute sécurité, assurant que seul vous et les destinataires autorisés puissent accéder aux informations.</li>
                <li><strong>Stockage Local</strong> : Nous ne stockons aucune donnée sur nos serveurs. Vos données restent entièrement sous votre contrôle, renforçant ainsi la confidentialité et la sécurité de vos informations.</li>
                <li><strong>Comptes Utilisateurs</strong> : En créant un compte, vous avez accès à des fonctionnalités supplémentaires telles qu'un espace de stockage sécurisé et la gestion simplifiée de vos données chiffrées.</li>
                </ul>
                <br></br>
                <h2><u>Notre Engagement en Matière de Sécurité</u></h2>
                <p>La sécurité est notre priorité absolue. Nous avons mis en place des mesures de sécurité rigoureuses pour protéger vos données contre toute menace potentielle. De la conception de notre application à son déploiement, nous avons pris soin de garantir la confidentialité et l'intégrité de vos informations à chaque étape du processus.</p>
                
                <p>Rejoignez-nous dans notre mission pour un monde en ligne plus sûr et plus sécurisé. Commencez dès aujourd'hui à protéger vos données avec SecureShare.</p>          
            </div>
        </div>
      </>
    );
}