import * as React from 'react';

export default function Page() {
    return(
        <>
        <title>Chiffrement</title>
        <meta name="description" content="Generated by create next app for Seconde Page" />
        <div className="bg-background">
          <div className="text-white">Chiffrement</div>
        </div>
      </>
    );
}